
[functions.google-auth-whitelist]
enabled = true
verify_jwt = true
import_map = "./functions/google-auth-whitelist/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/google-auth-whitelist/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/google-auth-whitelist/*.html" ]

[functions.verify-profile-password]
enabled = true
verify_jwt = true
import_map = "./functions/verify-profile-password/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/verify-profile-password/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/verify-profile-password/*.html" ]
